spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true  # 읽기 좋게 indentation 및 줄바꿈
    # show-sql: true  # 사용을 지양한다.
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
#logging:
#  level:
#    org:
#      hibernate: debug